/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TeacherPackage;

import connectionPackage.DBconnection;
import static connectionPackage.DBconnection.connect;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author halla
 */
public class TitleQuiz extends javax.swing.JFrame {

    String user;

    /**
     * Creates new form TitleQuiz
     */
    public TitleQuiz() {
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();

        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
    }

    public TitleQuiz(String user) {
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        ERRORTV.setText("");
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        this.user = user;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ERRORTV = new javax.swing.JLabel();
        TitleAddTextField = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();
        ADDBTN = new javax.swing.JButton();
        CANCELBTN = new javax.swing.JButton();
        CANCELBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1965, 1080));

        jPanel1.setLayout(null);

        ERRORTV.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ERRORTV.setForeground(new java.awt.Color(255, 0, 51));
        ERRORTV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ERRORTV.setText("jLabel1");
        jPanel1.add(ERRORTV);
        ERRORTV.setBounds(840, 380, 440, 20);
        jPanel1.add(TitleAddTextField);
        TitleAddTextField.setBounds(839, 320, 440, 50);

        Background.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon("D:\\NU School Files\\5th Term\\UpdateIM-master\\src\\IM PICS\\Add Title BG.png")); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 1965, 768);

        ADDBTN.setText("jButton1");
        ADDBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDBTNActionPerformed(evt);
            }
        });
        jPanel1.add(ADDBTN);
        ADDBTN.setBounds(940, 420, 240, 70);

        CANCELBTN.setText("jButton2");
        CANCELBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELBTNActionPerformed(evt);
            }
        });
        jPanel1.add(CANCELBTN);
        CANCELBTN.setBounds(940, 520, 240, 70);

        CANCELBTN1.setText("jButton2");
        CANCELBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELBTN1ActionPerformed(evt);
            }
        });
        jPanel1.add(CANCELBTN1);
        CANCELBTN1.setBounds(10, 20, 80, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public int getID(String user) {
        try {
            Connection con = connect();
            PreparedStatement pst = con.prepareStatement("SELECT * FROM Teacher_Account WHERE TA_Username = ?");
            pst.setString(1, user);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                return rs.getInt("TA_ID");
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("error");
            System.out.println(e);
        }

        return 0;
    }
    private void ADDBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDBTNActionPerformed
        try {
            Connection con = DBconnection.connect();
            PreparedStatement pst = con.prepareStatement("SELECT * FROM QuizesTitle WHERE TA_ID = ? AND QT_Title = ?");
            int mama = getID(user);
            pst.setInt(1, mama);
            pst.setString(2, TitleAddTextField.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                ERRORTV.setText("Title Already Exist");
            } else {
                pst.close();
                rs.close();
                pst = con.prepareStatement("INSERT INTO QuizesTitle(TA_ID,QT_Title,QT_CODEGENERATE) VALUES(?,?,?)");
                pst.setInt(1, mama);
                pst.setString(2, TitleAddTextField.getText());

                String easy = RandomString.digits + "ACEFGHJKLMNPQRUVWXYabcdefhijkprstuvwx";
                RandomString tickets = new RandomString(6, new SecureRandom(), easy);
                Connection checkcon = connect();
                PreparedStatement check = checkcon.prepareStatement("SELECT * FROM QuizesTitle WHERE TA_ID = ? AND QT_CODEGENERATE = ?");
                check.setInt(1, mama);
                check.setString(2, tickets.nextString());
                ResultSet checkSet = check.executeQuery();
                if (checkSet.next()) {
                    RandomString gen = new RandomString(8, ThreadLocalRandom.current());
                    pst.setString(3, gen.nextString());
                } else {
                    pst.setString(3, tickets.nextString());
                }
                pst.execute();
                    System.out.println("SUCCESS");
                AddExam exam = new AddExam(user, TitleAddTextField.getText());
                exam.setVisible(true);
                this.dispose();
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_ADDBTNActionPerformed

    private void CANCELBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELBTNActionPerformed
        try {
            TeacherQuizzes home = new TeacherQuizzes(user);
            home.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TitleQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CANCELBTNActionPerformed

    private void CANCELBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELBTN1ActionPerformed
       try {
            TeacherQuizzes home = new TeacherQuizzes(user);
            home.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TitleQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CANCELBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitleQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitleQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitleQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitleQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TitleQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDBTN;
    private javax.swing.JLabel Background;
    private javax.swing.JButton CANCELBTN;
    private javax.swing.JButton CANCELBTN1;
    private javax.swing.JLabel ERRORTV;
    private javax.swing.JTextField TitleAddTextField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
